### ISSUE TITLE
Add "webpack" feature

### ISSUE THREAD

**Issue by christopheranderson** [serverless/serverless-azure-functions#10]
Should add a feature which webpacks the contents before sending them to Azure for better cold start performance.

This is blocked on the latest Feb runtime going out.

**Comment by hoffmannjan** [comment]
anybody use serverless-webpack with serverless-azure-functions?

I was trying, but all I got deployed is bundled hander.js, without function.json so in azure-portal functions isn't visible.

**Comment by HyperBrain** [comment]
If someone checked Azure with `serverless-webpack`, please put the results in https://github.com/serverless-heaven/serverless-webpack/issues/128. I'll try to gather all working integrations and compatibility issues there, so that we can make support of the plugin possible with all providers. Until now the OpenWhisk plugin has been fully tested and is added to the compatibility table.
It would be great to have the Azure plugin in there too - of course with a fully working integration 😄

**Comment by HyperBrain** [comment]
@lostintangent Any news here? It would be great to test the provider plugin working with `serverless-webpack` and get it working properly. See my comment above.

**Comment by KosnIre** [comment]
Hey @HyperBrain I have been toying with `serverless-webpack` combined with `serverless-azure-functions`. It seems this is very important for Azure Functions because it's slow to load many small files (e.g. the npm_modules dir).

I was able to get the combo running successfully, but there is a small problem. You have to manually upload the `function.json` files to Azure. See [my writeup here](https://github.com/serverless/serverless-azure-functions/issues/93#issuecomment-350599037).

**Comment by HyperBrain** [comment]
Hi @KosnIre . That sounds good. 

Regarding the packaging of the JSON files in each package, you could use the `slsw.lib.serverless` object to add the function json files to each of the packages. If it would not be critical, that you add every json to each zip, you can fetch all function names easily in your webpack config:

```js
// webpack.conf.js
const slsw = require('serverless-webpack');

// Get the names of all functions from the current serverless instance
const allFuncNames = slsw.lib.serverless.service.getAllFunctions();

// Get the complete function objects from the serverless service.
const funcObjects = allFuncNames.map(allFuncNames, name => {
  return slsw.lib.serverless.service.getFuction(name);
});

// Now use the func vars above (or anything else retrieved from the serverless instance)
// to build the parameters for the webpack copy plugin to add all files you need.
```

As you have access to the complete serverless instance, you can use it to
retrieve anything from there - exactly as any serverless plugin would do.

**Comment by KosnIre** [comment]
Thanks @HyperBrain , the problem I am having with this solution is that `webpack-plugin-copy` seems to have no knowledge of the `serverless-webpack` setting `individually: true`. It keeps copying whatever I give it to the output of all my function .zip files. 

For example, If I give it a `to: hello` parameter, I get `hello/hello-function.json` in all my .zip files (not just `hello.zip`). If I leave the `to:` param off, I get `hello-function.json` in the root of all my .zip files. What I want to do is place one `<function-name>-function.json` file into each corresponding .zip when packaging individually with `serverless-webpack`.

But, I'm not here just to complain; I have an alternative:

I spent some time looking through the code and I think I have a working solution by having `serverless-azure-functions` use the hooks provided in `serverless-webpack` 4.0.0. I believe this makes sense because, since the `function.json` files are **required** by Microsoft Azure Functions, it should be on `serverless-azure-functions` to upload these.

I am working on cleaning up these changes and I will tag this issue in the PR when I create it. Hopefully, I can also provide a working example.

**Comment by HyperBrain** [comment]
> having serverless-azure-functions use the hooks provided in serverless-webpack 4.0.0

Great idea! That was exactly the reason why I introduced the plugin hooks, to let other plugins just do additional stuff at the right time.
However, if you miss a hook or need more fine-grained hook points, just let me know and I can see if I can add them to the webpack plugin. Additionally, the azure plugin should declare the webpack plugin then as optional dependency, so that, even if the webpack plugin is not used, it will continue to work.

**Comment by HyperBrain** [comment]
Hi everyone here... does the webpack integration with `serverless-webpack` work now? If yes, could someone please add the supported features to the provider table in `serverless-webpack's` README and comment in https://github.com/serverless-heaven/serverless-webpack/issues/128? Thanks.
