### ISSUE TITLE
Choose Linux over Windows container

### ISSUE THREAD

**Issue by celicoo** [serverless/serverless-azure-functions#121]
Is it possible to choose a Linux container over a Windows when I deploy a function?

Thank you.

**Comment by yzorg** [comment]
https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-on-Linux-Preview

I'm just passing through.  But it took me a while to find the preview link for functions on Linux (still in preview), and I thought it might help future readers.

Also, I think you're talking about Linux using "consumption model" (pricing).  They also have Linux via "bring your own containers" but that uses the earlier Azure AppService pricing model.  Asking because you mention container, but the consumption model you never "see" containers (the AF runtime uses them under the covers).  See https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-V2-hosting-options .
