### ISSUE TITLE
Vulnerability found in dependencies

### ISSUE THREAD

**Issue by huksley** [serverless/serverless-azure-functions#131]
When using this plugin as local development dependency (for example https://github.com/huksley/serverless-multicloud-update-addresses/)
both GitHub and npm report vulnerabilities found.

Here is the summary of vulnerabilities (output of `npm audit --parseable`)

```bash
review	hoek		moderate	> 4.2.0 < 5.0.0 || >= 5.0.3	Prototype pollution				https://npmjs.com/advisories/566	serverless-azure-functions>request>hawk>boom>hoek
review	hoek		moderate	> 4.2.0 < 5.0.0 || >= 5.0.3	Prototype pollution				https://npmjs.com/advisories/566	serverless-azure-functions>request>hawk>cryptiles>boom>hoek
review	hoek		moderate	> 4.2.0 < 5.0.0 || >= 5.0.3	Prototype pollution				https://npmjs.com/advisories/566	serverless-azure-functions>request>hawk>hoek
review	hoek		moderate	> 4.2.0 < 5.0.0 || >= 5.0.3	Prototype pollution				https://npmjs.com/advisories/566	serverless-azure-functions>request>hawk>sntp>hoek
review	static-eval	moderate	>=2.0.0				Sandbox Breakout / Arbitrary Code Execution	https://npmjs.com/advisories/548	serverless-azure-functions>jsonpath>static-eval
review	sync-exec	moderate	No patch available		Tmp files readable by other users		https://npmjs.com/advisories/310	serverless-azure-functions>az-login>copy-paste>sync-exec
```

**Comment by tbarlow12** [comment]
This looks like it was referencing `v0`. Closing for now, re-open if you have other issues

**Comment by G-Rath** [comment]
@tbarlow12 this is still an issue - installing `serverless-azure-functions` via `npm i -D serverless-azure-functions` gets me version 2.1.0 and 12 new unfixable vulnerabilities:

```
compare-gh-webhook-to-schema-function on  main is 📦 v0.0.0
❯ npm un serverless-azure-functions
removed 341 packages and audited 963 packages in 7.828s
found 0 vulnerabilities


compare-gh-webhook-to-schema-function on  main is 📦 v0.0.0 took 8s
❯ npm i -D serverless-azure-functions
... post install stuff ...

+ serverless-azure-functions@2.1.0
added 341 packages from 393 contributors and audited 1305 packages in 54.081s
found 12 vulnerabilities (6 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

I'm happy to help look into these and get them resolved, but it's likely going to require some discussion - I think the biggest blocker will be handling the node version supported by this package: currently `engines.node` is set to `>= 6` which blocks me from replacing `zip-folder` with a more updated package since it requires updating `archiver` to latest which requires Node `>= 10`.

Looking at your CI, you're currently only testing against node10 & node12, and have at least one dependency that requires `>= 8` (`open)` - I'm not fussed how you want to handle this (i.e just ignoring `engines.node`, bumping it in a non-major version, cutting a new major release, or removing it entirely), just so long as it's addressed ideally in a way that'll allow for quick releasing of patches :)
