### ISSUE TITLE
<function-name>/function.json temporary files created across deployment

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless-azure-functions#253]
To avoid collisions and to play nice with `git status` it'll be nicer if all temporary files are created within `<project-root>/.serverless` folder (e.g. it's the case for AWS deployments)

Also those files are not cleaned if deploys crashes in a middle for some reason, and as files are spread across different directories, it's more cumbersome to clean the introduced state manually.

**Comment by tbarlow12** [comment]
Is there any mechanism within the serverless framework for `finally` hooks? I'd like to set the cleanup to happen in such a hook so that the files always get cleaned up.

As far as putting the files within the `.serverless` folder, this would change the packaging & offline story significantly. Would make the offline story especially messy, just because `azure-functions-core-tools` expects to find the directories with `function.json` inside at the root of the project.

Probably won't address with this release, but we can discuss the change down the road

**Comment by medikoo** [comment]
> I'd like to set the cleanup to happen in such a hook so that the files always get cleaned up.

You mean that also when crash occurs? I guess the most reliable way would be attaching it `process.on('exit', ...)` and remove those files with _sync_ fs functions

> just because `azure-functions-core-tools` expects to find the directories with function.json inside at the root of the project.

I take it's needed only by _offline_ functionality which is baked on top of `azure-functions-core-tools` (?)

It appears we have a conflict here, as we're in context of Serverless Framework which has predefined convention of how functions are configured, and then we're relying on tool of which which functionality overlaps with Serverless, which demands different conventions (do I get this correct?)

Not sure if we can solve that cleanly, but first step of improvement could be to create those files only when we actually rely on `azure-functions-core-tools`. Then cleaning them up on process exit will make issue less apparent

**Comment by tbarlow12** [comment]
@medikoo in order to minimize the maintenance cost of this plugin, we rely on `azure-functions-core-tools` for offline as well as packaging and publishing of python/linux azure functions. We will most likely continue to increase the dependence on this tool so as to not duplicate work and ensure that these steps are performed in the way that Azure Functions is expecting them to be performed. In order for core-tools to work properly, it is expecting to see `functionName` directories at the root of the project. Going to close this for now, but open to further discussions in the future.

**Comment by medikoo** [comment]
Maybe then good direction would be, to make convention as set by `azure-functions-core-tools` a first class citizen.

So plugin will require users to put function configurations into `<function-name>/function.json` files, which will then be automatically propagated/translated for Serverless Framework  (so no functions config will have to be made in `serverless.yml`)
