### ISSUE TITLE
Compatibility issues with other Serverless plugins.

### ISSUE THREAD

**Issue by Nipol** [serverless/serverless-azure-functions#62]
[serverless-plugin-typescript#2 on Azure](https://github.com/graphcool/serverless-plugin-typescript/issues/2)

The issue is that projects written with the Serverless plugin do not work with the serverless-azure-function plugin.
Is that project optimized for the AWS plugin? Or does the serverless-azure-function plugin work differently?

I do not know what mechanism the `Serverless Core` was designed for, so I want to know where to fix the bug.

**Comment by cmatskas** [comment]
I installed, created and deployed on Azure just fine. I then tested my Function (HttpTrigger) using a number of tools (browser, curl, fiddler).

Could you please explain what's wrong? You say that it's not working for you but haven't provided any errors we can look at or specific issues. Therefore, it would be great if you could elaborate a bit so that we can either help you or fix the bug(s)

**Comment by Nipol** [comment]
@cmatskas You do not seem to have seen the issue I linked to. 😵 Please take a look at the link.

**Comment by maticko** [comment]
@Nipol look at #34 issue. Not sure how AWS deploy works, but this one creates the folder structure and then copies the original `handler` file + renames it from handler to index. So ignores whatever files packaging plugins created. So it assumes ALL your code is contained within one file and is also valid js. And after deploy, that newly created folder structure is left behind.
